### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by BillPlayz** [Marchay/doodstream-PHP-library#1]
Could we possibly get a video of an install i would like to add this to my site 
i use a  vps so that would be great thank you

**Comment by Marchay** [comment]
Create a new file named `doodstream.php` Copy paste the code from [here](https://raw.githubusercontent.com/Marchay/doodstream-PHP-library/main/doodstream.php) 

Then in any other file , use the following code to initialize the library:- 
``` php
<?php
  require('doodstream.php');
  $key = "your-key-here";
  $ds = new DoodstreamAPI();
  $ds->Setup($key);
```

Then add any functions which is there in [here](https://github.com/Marchay/doodstream-PHP-library/blob/main/README.md)

For example if you want to get your account info , add this code (reference in the above link):-
```php
$result = $ds->AccountInfo();
print_r($result); // will output the result
```

**Comment by BillPlayz** [comment]
First thank you for replying am very new to this so all the help is great i have a few questions with the first link do i add my own doodstream api key or do i add that somewhere else 

i would need this to search my files if the name of that movie/tv  is not found then copy/ clone it from another user and plus make a folder and rename that folder then TMDB id of that movie/ tv show 

last question how would i go about adding to my website sorry for all the questions 

this is my api key for doodstream ---remove---

**Comment by Marchay** [comment]
Please do not post your doodstream api key in public, go in settings and change it right now. Give me some form of an id or email so that I can contact and talk with you further in much more detail.

**Comment by BillPlayz** [comment]
Sure thing sorry about that my email is --removed-- I look forward to ur email
