### ISSUE TITLE
how can i retrieve data from API

### ISSUE THREAD

**Issue by kasunkalmith** [Marchay/doodstream-PHP-library#2]
{"msg":"OK","server_time":"2021-09-24 12:55:51","status":200,"result":[{"download_url":"https://dood.la/d/r948435345ct6uoq66c","protected_embed":"https://dood.la/e/5rt5pcys3453wots16h734328zzujlweprlecdr0","protected_dl":"https://dood.la/d/mot8qokw77234247ll3453535352pfwcrh77virbann7gkfa","title":"34535"}]}

after that how can i retrieve data from  API.
example like 
$protected_embed
$download_url

**Comment by Marchay** [comment]
API sends result in JSON format, so you have to parse the json data into array which can be done using `json_decode`
If you have got that data result in a variable (let's assume it's called result), then you can do 

```
//assuming you got the result from API in a variable called $result
$info = $json_decode($result, true);
$protected_embed = $info["result"][0]["protected_embed"];
$download_url = $info["result"][0]["download_url"];
```

**Comment by kasunkalmith** [comment]
thank you very much @Marchay. does it have any method to upload videos to folder using API.

**Comment by Marchay** [comment]
> thank you very much @Marchay. does it have any method to upload videos to folder using API.

Unfortunately there is no direct way to upload file into a folder (except Remote Upload). The only way right now would be to directly upload the file into account using api then use the Clone API to copy the file inside the required folder.
